// Objective-C implementation file — compiled once by CGo, no duplication.
// _cgo_export.h is generated by CGo and provides the exported Go declarations.

#import <Cocoa/Cocoa.h>
#include "_cgo_export.h"
#include <stdlib.h>

@interface NSApplication (DockMenu)
- (void)setDockMenu:(NSMenu *)menu;
@end

@interface DockMenuHandler : NSObject
- (void)newWindow:(id)sender;
- (void)openFile:(id)sender;
- (void)openRecent:(id)sender;
@end

@implementation DockMenuHandler
- (void)newWindow:(id)sender { dockMenuNewWindow(); }
- (void)openFile:(id)sender { dockMenuOpenFile(); }
- (void)openRecent:(id)sender {
    NSString *path = [(NSMenuItem*)sender representedObject];
    if (path) {
        dockMenuOpenRecent((char*)[path UTF8String]);
    }
}
@end

static DockMenuHandler *handler = nil;
static NSMenu *_dockMenu = nil;

void setupDockMenu(void) {
    dispatch_async(dispatch_get_main_queue(), ^{
        if (!handler) handler = [[DockMenuHandler alloc] init];

        NSMenu *menu = [[NSMenu alloc] initWithTitle:@""];

        NSMenuItem *openItem = [[NSMenuItem alloc] initWithTitle:@"Open..." action:@selector(openFile:) keyEquivalent:@""];
        [openItem setTarget:handler];
        [menu addItem:openItem];

        NSMenuItem *newItem = [[NSMenuItem alloc] initWithTitle:@"New Window" action:@selector(newWindow:) keyEquivalent:@""];
        [newItem setTarget:handler];
        [menu addItem:newItem];

        [menu addItem:[NSMenuItem separatorItem]];

        NSMenuItem *recentHeader = [[NSMenuItem alloc] initWithTitle:@"Recent" action:nil keyEquivalent:@""];
        [recentHeader setEnabled:NO];
        [menu addItem:recentHeader];

        NSMenuItem *noneItem = [[NSMenuItem alloc] initWithTitle:@"No Recent Files" action:nil keyEquivalent:@""];
        [noneItem setEnabled:NO];
        [noneItem setTag:999];
        [menu addItem:noneItem];

        [[NSApplication sharedApplication] setDockMenu:menu];
        _dockMenu = menu;
    });
}

void updateDockRecentFiles(const char **paths, int count) {
    // Copy paths into NSStrings synchronously before returning,
    // because Go will free the C strings once this function returns.
    NSMutableArray *recentPaths = [NSMutableArray arrayWithCapacity:count];
    for (int i = 0; i < count; i++) {
        NSString *path = [NSString stringWithUTF8String:paths[i]];
        if (path) {
            [recentPaths addObject:path];
        }
    }
    // Free the individual C strings (allocated by C.CString in Go).
    // Do NOT free(paths) — the array itself is Go-allocated.
    for (int i = 0; i < count; i++) {
        free((void*)paths[i]);
    }

    dispatch_async(dispatch_get_main_queue(), ^{
        NSMenu *menu = _dockMenu;
        if (!menu) return;

        NSInteger startIdx = -1;
        for (NSInteger i = 0; i < [menu numberOfItems]; i++) {
            if ([[menu itemAtIndex:i] tag] == 999) {
                startIdx = i;
                break;
            }
        }

        if (startIdx >= 0) {
            while ([menu numberOfItems] > startIdx) {
                [menu removeItemAtIndex:startIdx];
            }
        }

        if (recentPaths.count == 0) {
            NSMenuItem *noneItem = [[NSMenuItem alloc] initWithTitle:@"No Recent Files" action:nil keyEquivalent:@""];
            [noneItem setEnabled:NO];
            [noneItem setTag:999];
            [menu addItem:noneItem];
            return;
        }

        for (NSString *path in recentPaths) {
            NSString *title = [path lastPathComponent];
            if (!title) title = @"";
            NSMenuItem *item = [[NSMenuItem alloc] initWithTitle:title action:@selector(openRecent:) keyEquivalent:@""];
            [item setTarget:handler];
            [item setRepresentedObject:path];
            [item setTag:999];
            [menu addItem:item];
        }
    });
}
