// Objective-C implementation file — compiled once by CGo, no duplication.
// _cgo_export.h is generated by CGo and provides the goCloseSheetResult declaration.

#import <Cocoa/Cocoa.h>
#include "_cgo_export.h"

static NSMutableDictionary *_fmdTargets = nil;

@interface FastMDCloseTarget : NSObject
@property unsigned int did;
@property (strong) NSTextField *nameField;
@property (strong) NSTextField *locLabel;
@property (copy) NSString *selectedDir;
- (void)changeDir:(id)sender;
@end

@implementation FastMDCloseTarget
- (void)changeDir:(id)sender {
    NSOpenPanel *op = [NSOpenPanel openPanel];
    op.canChooseFiles = NO;
    op.canChooseDirectories = YES;
    op.canCreateDirectories = YES;
    op.prompt = @"选择";
    if (self.selectedDir)
        op.directoryURL = [NSURL fileURLWithPath:self.selectedDir];
    // runModal works on top of an NSAlert sheet (application-modal)
    if ([op runModal] == NSModalResponseOK && op.URL) {
        self.selectedDir = op.URL.path;
        self.locLabel.stringValue = op.URL.lastPathComponent;
    }
}
@end

static void _doShowCloseSheet(unsigned int did, NSWindow *window,
                               NSString *filename, NSString *dir) {
    if (!_fmdTargets) _fmdTargets = [NSMutableDictionary new];

    FastMDCloseTarget *tgt = [FastMDCloseTarget new];
    tgt.did = did;
    tgt.selectedDir = dir;
    _fmdTargets[@(did)] = tgt;

    NSAlert *alert = [NSAlert new];
    NSString *base = filename.stringByDeletingPathExtension;
    if (!base.length) base = @"未命名";
    alert.messageText = [NSString stringWithFormat:@"你要保留此新文稿 \"%@\" 吗？", base];
    alert.informativeText = @"你可以选择保存更改，或者立即删除此文稿。此操作无法撤销。";
    alert.alertStyle = NSAlertStyleWarning;

    // First added = rightmost = default (blue)
    [alert addButtonWithTitle:@"保存"];  // NSAlertFirstButtonReturn  (1000)
    [alert addButtonWithTitle:@"取消"];  // NSAlertSecondButtonReturn (1001)
    [alert addButtonWithTitle:@"删除"];  // NSAlertThirdButtonReturn  (1002)

    NSButton *delBtn = alert.buttons[2];
    if (@available(macOS 14.0, *)) {
        delBtn.hasDestructiveAction = YES;
    } else {
        delBtn.contentTintColor = [NSColor systemRedColor];
    }

    // ── Accessory view: filename + location ───────────────────────────────
    NSView *acc = [[NSView alloc] initWithFrame:NSMakeRect(0, 0, 350, 58)];

    NSTextField *lbl1 = [NSTextField labelWithString:@"保存为："];
    lbl1.frame = NSMakeRect(0, 36, 58, 18);
    lbl1.alignment = NSTextAlignmentRight;

    NSTextField *nameField = [[NSTextField alloc] initWithFrame:NSMakeRect(64, 32, 286, 24)];
    nameField.stringValue = filename.length ? filename : @"untitled.md";
    nameField.placeholderString = @"文件名";
    tgt.nameField = nameField;

    NSTextField *lbl2 = [NSTextField labelWithString:@"位置："];
    lbl2.frame = NSMakeRect(0, 8, 58, 18);
    lbl2.alignment = NSTextAlignmentRight;

    NSString *dirName = dir.lastPathComponent.length ? dir.lastPathComponent : @"下载";
    NSTextField *locLabel = [NSTextField labelWithString:dirName];
    locLabel.frame = NSMakeRect(64, 8, 180, 18);
    locLabel.editable = NO;
    locLabel.bezeled = NO;
    locLabel.drawsBackground = NO;
    locLabel.lineBreakMode = NSLineBreakByTruncatingMiddle;
    tgt.locLabel = locLabel;

    NSButton *changeBtn = [NSButton buttonWithTitle:@"更改…"
                                            target:tgt
                                            action:@selector(changeDir:)];
    changeBtn.frame = NSMakeRect(250, 4, 90, 24);
    changeBtn.bezelStyle = NSBezelStyleRounded;

    [acc addSubview:lbl1];
    [acc addSubview:nameField];
    [acc addSubview:lbl2];
    [acc addSubview:locLabel];
    [acc addSubview:changeBtn];
    alert.accessoryView = acc;

    [alert beginSheetModalForWindow:window completionHandler:^(NSModalResponse ret) {
        FastMDCloseTarget *t = _fmdTargets[@(did)];
        [_fmdTargets removeObjectForKey:@(did)];

        if (ret == NSAlertFirstButtonReturn) {
            NSString *fname = t.nameField.stringValue;
            if (!fname.length) fname = @"untitled.md";
            if (![fname.pathExtension.lowercaseString isEqualToString:@"md"])
                fname = [fname stringByAppendingPathExtension:@"md"];
            NSString *path = [t.selectedDir stringByAppendingPathComponent:fname];
            goCloseSheetResult(did, 2, (void *)path.UTF8String);
        } else if (ret == NSAlertThirdButtonReturn) {
            goCloseSheetResult(did, 1, NULL);
        } else {
            goCloseSheetResult(did, 0, NULL);
        }
    }];
}

// Entry point called from Go. Copies C strings into NSStrings immediately
// (caller may free after return), then dispatches to the main thread.
void showCloseSheet(unsigned int did, void *winPtr,
                    const char *fnC, const char *dirC) {
    NSWindow *win = (__bridge NSWindow *)winPtr;
    NSString *fn  = (fnC  && fnC[0])  ? [NSString stringWithUTF8String:fnC]  : @"untitled.md";
    NSString *dir = (dirC && dirC[0]) ? [NSString stringWithUTF8String:dirC]
                                      : [NSHomeDirectory() stringByAppendingPathComponent:@"Downloads"];
    dispatch_async(dispatch_get_main_queue(), ^{
        _doShowCloseSheet(did, win, fn, dir);
    });
}
